# Generated by Django 5.0.2 on 2024-12-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionsimple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsimple',
            name='txn_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
