# Generated by Django 5.0.2 on 2024-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactionsimple_txn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsimple',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
