# Generated by Django 5.0.2 on 2024-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionsimple_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Payment'), (5, 'Received'), (6, 'Sent')]),
        ),
        migrations.DeleteModel(
            name='TransactionSimple',
        ),
    ]
